kind: Service
apiVersion: v1
metadata:
  name: dotnet-grpc-service
spec:
  type: NodePort
  selector:
    app: dotnet-grpc
  ports:
    - port: 50031
      targetPort: cs-port
      nodePort: 30031
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: dotnet-grpc-deployment
spec:
  selector:
    matchLabels:
      app: dotnet-grpc
  template:
    metadata:
      labels:
        app: dotnet-grpc
    spec:
      containers:
        - name: dotnet-grpc-pod
          image: dotnet-grpc-image
          imagePullPolicy: Never
          ports:
            - containerPort: 3031
              name: cs-port